// Currency
export const FETCH_CURRENCY = 'FETCH_CURRENCY';
export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
export const RECIEVE_COUNTRIES = 'RECIEVE_COUNTRIES';
export const REQUEST_RATES = 'REQUEST_RATES';
export const RECIEVE_RATES = 'RECIEVE_RATES';
